Linux runtime code
n7space/TASTE-Linux-Runtime pull request #1
Opened 2021-08-19 09:04 UTC by rphh

2021-09-07 07:08 UTC, Glamhoth requested changes
Additional comments:
1) This repo is missing `.clang-format`, you can copy one from our other repo (TASTE-Runtime-Common i.e.)
2) Docs are missing

2021-09-07 07:08 UTC, Glamhoth commented on src/thread.cpp
> +  m_method = nullptr;
Shouldn't this be `m_method = method`?

2021-09-07 09:46 UTC, rphh commented on CMakeLists.txt
> +set(CMAKE_C_STANDARD 99)
Done

2021-09-07 09:47 UTC, rphh commented on src/timer.h
> +  Timer() = default;
True, removed.

2021-09-07 09:58 UTC, rphh commented on CMakeLists.txt
> +  elseif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
fixed.

2021-09-07 09:59 UTC, rphh commented on CMakeLists.txt
> +  target_compile_options(common_build_options INTERFACE ${PROJECT_WARNINGS})
fixed.

2021-09-07 09:59 UTC, rphh commented on src/queue.h
> +  void put(const Request<PARAMETER_SIZE> &request) {
Implementation outside class declaration is best what I can do.

2021-09-07 09:59 UTC, rphh commented on src/queue.h
> +
CHanged.

2021-09-07 10:03 UTC, rphh commented on src/timer.h
> +      start = std::chrono::steady_clock::now();
Renamed

2021-09-07 10:03 UTC, rphh commented on src/thread.h
> +  Thread(int priority, size_t stack_size);
Done.

2021-09-07 10:06 UTC, rphh commented on src/thread.cpp
> +Thread::Thread(int priority, size_t stack_size)
No. It is not necessary in TASTE. Thread shall be created, started and that's everything.

2021-09-07 10:11 UTC, rphh commented on src/thread.cpp
> +  m_method = nullptr;
No, comment added.

2021-09-07 12:09 UTC, Glamhoth commented on src/queue.h
> +  void put(const Request<PARAMETER_SIZE> &request) {
ack

2021-09-07 12:14 UTC, Glamhoth commented on src/Queue.h
> +    Queue(size_t max_elements);
const arg

2021-09-07 12:14 UTC, Glamhoth commented on src/Queue.h
> +    Queue(const Queue&) = delete;
docs

2021-09-07 12:14 UTC, Glamhoth commented on src/Queue.h
> +    const size_t m_max_elements;
docs

2021-09-07 12:14 UTC, Glamhoth commented on src/Lock.h
> + * @brief    Implemntation of lock required by TASTE function blocks.
misspell

2021-09-07 12:14 UTC, Glamhoth commented on src/Lock.h
> +    /// @release lock
@brief

2021-09-07 12:14 UTC, Glamhoth commented on src/Lock.h
> +    Lock(const Lock&) = delete;
docs

2021-09-07 12:14 UTC, Glamhoth commented on src/Lock.h
> +    std::mutex m_mutex;
docs

2021-09-07 12:14 UTC, Glamhoth commented on src/lock.h
> +  ~Lock();
it's removed, ok

2021-09-07 12:19 UTC, Glamhoth commented on src/Timer.h
> +        auto diff = interval - jitter;
const

2021-09-07 12:19 UTC, Glamhoth commented on src/Thread.h
> +    Thread(const Thread&) = delete;
docs

2021-09-07 12:19 UTC, Glamhoth commented on src/Thread.h
> +    void create_thread(void* (*fn)(void*), void* param);
do we document privates?

2021-09-07 12:19 UTC, Glamhoth commented on src/thread.cpp
> +Thread::Thread(int priority, size_t stack_size)
I meant that we should keep the same order of functions in both .h and .cpp files

2021-09-07 12:20 UTC, Glamhoth commented on src/thread.cpp
> +  m_method = nullptr;
ack

2021-09-07 13:57 UTC, rphh commented on src/queue.h
> +    std::unique_lock<std::mutex> lock(m_mutex);
RAII

2021-09-07 14:03 UTC, rphh commented on src/queue.h
> +        lock.unlock();
I don't see an issue here:
`std::unique_lock<std::mutex> lock(m_mutex);` // locks m_mutex
`m_cv.wait(lock);` // unlocks the mutex, waits for notify, locks the mutex again, then returns

https://en.cppreference.com/w/cpp/thread/condition_variable

2021-09-07 14:23 UTC, rphh commented on src/Timer.h
> +        auto diff = interval - jitter;
done

2021-09-07 14:23 UTC, rphh commented on src/Lock.h
> +    std::mutex m_mutex;
this is private

2021-09-07 14:23 UTC, rphh commented on src/Lock.h
> +    /// @release lock
fixed

2021-09-07 14:23 UTC, rphh commented on src/Lock.h
> + * @brief    Implemntation of lock required by TASTE function blocks.
fixed

2021-09-07 14:23 UTC, rphh commented on src/Queue.h
> +    const size_t m_max_elements;
this is private

2021-09-07 14:24 UTC, rphh commented on src/Queue.h
> +    Queue(size_t max_elements);
changed

2021-09-07 14:24 UTC, rphh commented on src/thread.cpp
> +Thread::Thread(int priority, size_t stack_size)
Fixed

2021-09-07 14:54 UTC, rphh commented on src/lock.h
> +  Lock();
changed

2021-09-07 14:55 UTC, rphh commented on src/request.h
> +  Request(const Request &other) : m_length(other.m_length) {
I've changed the array to std::array, now the constructors are defaulted,

2021-09-07 14:55 UTC, rphh commented on src/Queue.h
> +    Queue(const Queue&) = delete;
Done

2021-09-07 14:55 UTC, rphh commented on src/Lock.h
> +    Lock(const Lock&) = delete;
DOne

2021-09-07 14:55 UTC, rphh commented on src/Thread.h
> +    Thread(const Thread&) = delete;
Done

2021-09-07 14:56 UTC, rphh commented on src/Thread.h
> +    void create_thread(void* (*fn)(void*), void* param);
No

2021-09-08 11:23 UTC, Glamhoth commented on src/queue.h
> +    std::unique_lock<std::mutex> lock(m_mutex);
Ah, it's `unique_lock`, ok then

2021-09-08 11:24 UTC, Glamhoth commented on src/queue.h
> +        lock.unlock();
You're right, I didn't notice that this is `unique_lock` and not our `Lock`

2021-09-08 11:28 UTC, Glamhoth approved these changes

2021-09-08 15:05 UTC, Lurkerpas commented on src/Timer.h
> +    auto currentTime = std::chrono::steady_clock::now();
I would call it reference time

2021-09-08 15:05 UTC, Lurkerpas commented on src/Timer.h
> +        const auto jitter = std::chrono::steady_clock::now() - currentTime;
delta? elapsed?

2021-09-09 07:34 UTC, rphh commented on src/Timer.h
> +    auto currentTime = std::chrono::steady_clock::now();
done

2021-09-09 07:34 UTC, rphh commented on src/Timer.h
> +        const auto jitter = std::chrono::steady_clock::now() - currentTime;
changed to elapsedTime

2021-09-09 09:56 UTC, Lurkerpas approved these changes

2021-09-09 10:27 UTC, merged